# Generated by Django 5.1.1 on 2024-09-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glofox', '0002_users_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('class_instance', 'member', 'date'), name='unique_booking'),
        ),
    ]
